sonar.sources=screens
sonar.tests=__tests__
sonar.exclusions=node_modules/**,coverage/**,assets/**,**/*.config.js,babel.config.js,jest.setup.js,index.ts
sonar.cpd.exclusions=screens/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=screens/common/ForgotPasswordScreen.tsx,screens/common/HomeScreen.tsx,screens/common/LoginScreen.tsx,screens/common/NotificationScreen.tsx,screens/common/ResetPasswordScreen.tsx,screens/common/SettingScreen.tsx,screens/common/SignUpScreen.tsx,screens/common/StartScreen.tsx,screens/common/WalkthroughScreen.tsx,screens/organizer/AddLocation.tsx,screens/organizer/AddTask.tsx,screens/organizer/CreateEvent.tsx,screens/organizer/EventsTasks.tsx,screens/organizer/MemberList.tsx,screens/organizer/TaskDetail.tsx,screens/staff/MapList.tsx,screens/staff/MapView.tsx,screens/staff/TaskDetail.tsx,screens/staff/TodayTask.tsx


